// Import environment variables from Vite
const BASE_URL = import.meta.env.VITE_API_BASE_URL;
const STUDENT_LOGIN_ENDPOINT = import.meta.env.VITE_STUDENTS_LOGIN_ENDPOINT;
const TEACHERS_ENDPOINT = import.meta.env.VITE_TEACHERS_ENDPOINT;
const ADMIN_LOGIN_ENDPOINT = import.meta.env.VITE_ADMIN_LOGIN_ENDPOINT;
const TEACHER_LOGIN_ENDPOINT = import.meta.env.VITE_TEACHER_LOGIN_ENDPOINT;
const STUDENTS_ENDPOINT = import.meta.env.VITE_STUDENTS_ENDPOINT;
const USER_ENDPOINT = import.meta.env.VITE_USER_ENDPOINT;
const LOGOUT = import.meta.env.VITE_FETCH_DATA_ENDPOINT;
const WEBSOCKET_ENDPOINT = import.meta.env.VITE_WEBSOCKET_ENDPOINT;
const REFRESH_TOKEN_ENDPOINT = import.meta.env.VITE_REFRESHTOKEN_ENDPOINT;
const COURSES_ENDPOINT = import.meta.env.VITE_COURSES_ENDPOINT;
const COHORT_ENDPOINT = import.meta.env.VITE_COHORT_ENDPOINT;
const CURRICULUM_ENDPOINT = import.meta.env.VITE_CURRICULUM_ENDPOINT;
const TIMETABLE_ENDPOINT = import.meta.env.VITE_TIMETABLE_ENDPOINT;
const ASSIGNMENT_ENDPOINT = import.meta.env.VITE_ASSIGNMENT_ENDPOINT;
const PAYMENT_ENDPOINT = import.meta.env.VITE_PAYMENT_ENDPOINT;
const REVIEW_ENDPOINT = import.meta.env.VITE_REVIEW_ENDPOINT;
const CHATROOM_ENDPOINT = import.meta.env.VITE_CHATROOM_ENDPOINT;
const ENQUIRY_ENDPOINT = import.meta.env.VITE_ENQUIRY_ENDPOINT;
const FEEDBACKS_ENDPOINT = import.meta.env.VITE_FEEDBACKS_ENDPOINT;
const CODE_AUTHENTICATOR = import.meta.env.VITE_CODE_AUTHENTICATOR;
const STORE_CODE = import.meta.env.VITE_STORE_CODE;
const PASSWORD_LINK = import.meta.env.VITE_PASSWORD_LINK;
const RESET_PASSWORD = import.meta.env.VITE_RESET_PASSWORD;
const PAYSTACK_PAYMENT = import.meta.env.VITE_PAYSTACK_PAYMENT;
const PAYSTACK_INIT = import.meta.env.VITE_PAYSTACK_INIT;
const ANNOUNCEMENT = import.meta.env.VITE_ANNOUNCEMENT;
const MARK_TIMETABLE = import.meta.env.VITE_MARK_TIMETABLEDONE;
const CREATE_TEACHER = import.meta.env.VITE_CREATE_TEACHER;
const CREATE_STUDENT = import.meta.env.VITE_CREATE_STUDENT;
const ACADEMIC_YEAR = import.meta.env.VITE_ACADEMIC_YEARS;
const ACADEMIC_TERM = import.meta.env.VITE_ACADEMIC_TERM;
const CLASS_LEVEL = import.meta.env.VITE_ACADEMIC_CLASSES;
const SUBJECT = import.meta.env.VITE_SUBJECT;
const CHANGEPASS = import.meta.env.VITE_CHANGE_PASSWORD;
const REGISTRATION_CODE = import.meta.env.VITE_REGISTRATION_CODE;

const endpoints = {
  LOGIN: {
    STUDENT: `${BASE_URL}${STUDENT_LOGIN_ENDPOINT}`,
    ADMIN: `${BASE_URL}${ADMIN_LOGIN_ENDPOINT}`,
    TEACHER: `${BASE_URL}${TEACHER_LOGIN_ENDPOINT}`
  },
  USER: `${BASE_URL}${USER_ENDPOINT}`,
  TEACHERS: `${BASE_URL}${TEACHERS_ENDPOINT}`,
  STUDENTS: `${BASE_URL}${STUDENTS_ENDPOINT}`,
  LOGOUT: `${BASE_URL}${LOGOUT}`,
  REFRESH_TOKEN: `${BASE_URL}${REFRESH_TOKEN_ENDPOINT}`,
  WEBSOCKET_ENDPOINT,
  COURSES: `${BASE_URL}${COURSES_ENDPOINT}`,
  COHORT: `${BASE_URL}${COHORT_ENDPOINT}`,
  CURRICULUM: `${BASE_URL}${CURRICULUM_ENDPOINT}`,
  TIMETABLE: `${BASE_URL}${TIMETABLE_ENDPOINT}`,
  ASSIGNMENT: `${BASE_URL}${ASSIGNMENT_ENDPOINT}`,
  PAYMENT: `${BASE_URL}${PAYMENT_ENDPOINT}`,
  REVIEW: `${BASE_URL}${REVIEW_ENDPOINT}`,
  CHATROOM: CHATROOM_ENDPOINT,
  ENQUIRIES: `${BASE_URL}${ENQUIRY_ENDPOINT}`,
  FEEDBACKS: `${BASE_URL}${FEEDBACKS_ENDPOINT}`,
  CODE_AUTH: `${BASE_URL}${CODE_AUTHENTICATOR}`,
  STORE_CODE: `${BASE_URL}${STORE_CODE}`,
  PASSWORD_LINK: `${BASE_URL}${PASSWORD_LINK}`,
  RESET_PASSWORD: `${BASE_URL}${RESET_PASSWORD}`,
  PAYSTACK_PAYMENT: `${BASE_URL}${PAYSTACK_PAYMENT}`,
  PAYSTACK_INIT: `${BASE_URL}${PAYSTACK_INIT}`,
  ANNOUNCEMENT: `${BASE_URL}${ANNOUNCEMENT}`,
  MARK_TIMETABLE: `${BASE_URL}${MARK_TIMETABLE}`,
  CREATE_TEACHER: `${BASE_URL}${CREATE_TEACHER}`,
  CREATE_STUDENT: `${BASE_URL}${CREATE_STUDENT}`,
  ACADEMIC_YEARS: `${BASE_URL}${ACADEMIC_YEAR}`,
  CURRENT_ACADEMIC_YEAR: `${BASE_URL}${ACADEMIC_YEAR}/current`,
  ACADEMIC_TERM: `${BASE_URL}${ACADEMIC_TERM}`,
  CLASS_LEVEL: `${BASE_URL}${CLASS_LEVEL}`,
  SUBJECT: `${BASE_URL}${SUBJECT}`,
  CHANGEPASS: `${BASE_URL}${CHANGEPASS}`,
  GET_A_TEACHER: `${BASE_URL}/teacher`,
  REGISTRATION_CODE: `${BASE_URL}${REGISTRATION_CODE}`
};

export { endpoints };
